
''' removeCsvColumn
- remove the given column (by name or indice) in the CSV using 3 different technics
pandas accepts name but csv only accepts indice (0-based)
- note that we turn string handling csv.QUOTE_NONE and quotechar to ' instead of "
to match the original contents generated by the FQM procedure
created : marcel.bechtiger@domain-sa.ch - 20231023
modified :
'''

import pandas as pd
import csv

csvFile = 'DOCUMENT.csv'
csvColDelimiter = '#'
columnToRemove = 'RESUME'
columnNbToRemove = 54 # csv is 0 based
outCsvFile1 = 'DOCUMENT_1.csv'
outCsvFile2 = 'DOCUMENT_2.csv'
outCsvFile3 = 'DOCUMENT_3.csv'

########## 1) using pandas drop()

if True:
    data = pd.read_csv(csvFile, sep=csvColDelimiter)
    print(len(data), 'lines in csv')
    #print("Original CSV: \n")
    #print(data.head(20))
    data.drop(columnToRemove, inplace=True, axis=1)
    #print("CSV after deleting column:\n")
    #print(data.head(20))
    data.to_csv(outCsvFile1, sep=csvColDelimiter, index=False, quoting=csv.QUOTE_NONE,
        escapechar='\\', quotechar='\'')

########## 2) using pandas pop()

if True:
    data = pd.read_csv(csvFile, sep=csvColDelimiter)
    print(len(data), 'lines in csv')
    #print("Original CSV: \n")
    #print(data.head(20))
    data.pop(columnToRemove)
    #print("\nCSV Data after deleting column:\n")
    #print(data.head(20))
    data.to_csv(outCsvFile2, sep=csvColDelimiter, index=False, quoting=csv.QUOTE_NONE,
        escapechar='\\', quotechar='\'')

########## 3) using csv rewrite

if True:
    rowCount = 0 # Current amount of rows processed
    csv.register_dialect('xyz', delimiter=csvColDelimiter, quoting=csv.QUOTE_NONE,
        escapechar='\\', quotechar='\'')
    source = open(csvFile, 'r')
    reader = csv.reader(source, delimiter=csvColDelimiter)
    result = open(outCsvFile3, 'w', newline='')
    writer = csv.writer(result, dialect='xyz')
    for row in reader:
        rowCount += 1
        del row[columnNbToRemove]
        writer.writerow(row)
    print(rowCount, 'lines in csv')
    source.close()
    result.close()

##########
