*------------------------------------
ACTUAL_DATA_MODEL;*          TOUR
*------------------------------------
*
WORD_LIST=ENORANGE,+
   TYPE=EXACT_BINARY,+
   PRECISION=5,+
   WORDS=(1000:4000,4500:7500,10000:12000);
*
WORD_LIST=JOB_LIST,+
   TYPE=CHAR,+
   WORDS=('Administrative Assistant','Clerk','Manager','Operator',+
'President','Programmer','Salesman','Secretary','Vice-President');
*
WORD_LIST=RELATIONSHIP_LIST,+
   TYPE=CHAR,+
   WORDS=('CHILD','FATHER','HUSBAND','MOTHER','OTHER','WIFE');
*
CODE_LIST=SINGULAR_EXCEPTIONS_ENGLISH,+
   CODES=(+
'DALLAS'='DALLAS');
*
CODE_LIST=STATE_ABBS,+
   CODES=(+
'AK'='ALASKA','AL'='ALABAMA','AR'='ARKANSAS','AZ'='ARIZONA','CA'='CALIFORNIA'+
,'CO'='COLORADO','CT'='CONNECTICUT','DC'='DISTRICT OF COLUMBIA','DE'=+
'DELAWARE','FL'='FLORIDA','GA'='GEORGIA','HI'='HAWAII','IA'='IOWA','ID'=+
'IDAHO','IL'='ILLINOIS','IN'='INDIANA','KS'='KANSAS','KY'='KENTUCKY','LA'=+
'LOUISIANA','MA'='MASSACHUSETTS','MD'='MARYLAND','ME'='MAINE','MI'='MICHIGAN'+
,'MN'='MINNESOTA','MO'='MISSOURI','MS'='MISSISSIPPI','MT'='MONTANA','N/A'=+
'NOT APPLICABLE','NC'='NORTH CAROLINA','ND'='NORTH DAKOTA','NE'='NEBRASKA',+
'NH'='NEW HAMPSHIRE','NJ'='NEW JERSEY','NM'='NEW MEXICO','NV'='NEVADA','NY'=+
'NEW YORK','OH'='OHIO','OK'='OKLAHOMA','OR'='OREGON','PA'='PENNSYLVANIA','RI'+
='RHODE ISLAND','SC'='SOUTH CAROLINA','SD'='SOUTH DAKOTA','TN'='TENNESSEE',+
'TX'='TEXAS','UT'='UTAH','VA'='VIRGINIA','VT'='VERMONT','WA'='WASHINGTON',+
'WI'='WISCONSIN','WV'='WEST VIRGINIA','WY'='WYOMING');
*
THESAURUS_DATA_CONTROL_SET=CODATA,+
   VERIFY=YES,+
   SWITCH=($PREFER),+
   THESAURUS=TTOUR.COMPANY;
*
SEARCH_CONTROL_SET=COSEARCH,+
   ENTIRE_VALUE=YES,+
   PRECISION=30,+
   THESAURUS=TTOUR.COMPANY,+
   SWITCH_SEARCH=($PREFER),+
   NOTIFY_SEARCH=($PREFER),+
   RAISE_TERMS=YES,+
   TEXT=YES;
*
SEARCH_CONTROL_SET=ITIN_SEARCH,+
   STOP=(NUMBERS,DM_STOP_WORDS),+
   BREAK=(NON_GRAPHIC,NON_TEXTUAL),+
   SUB_BREAK=('-'),+
   SINGULAR=YES,+
   PRECISION=30,+
   RAISE_TERMS=YES,+
   BLANK_CONTROL=YES,+
   TEXT=YES;
*
SEARCH_CONTROL_SET=RAISED,+
   PRECISION=30,+
   RAISE_TERMS=YES,+
   TEXT=NO;
*
SEARCH_CONTROL_SET=SPEEDSEARCH,+
   PRECISION=30,+
   RAISE_TERMS=YES,+
   FILTER=$PADB(CNAME[1:$MIN(4,$MATCH(',',CNAME)-1)],4)// $PADB(CNAME[$MATCH+
(',',CNAME)+2:$MIN($LC(CNAME), $MATCH(',',CNAME)+5)],4),+
   TEXT=NO;
*
SEARCH_CONTROL_SET=STREET,+
   STOP=(NUMBERS),+
   PRECISION=30,+
   RAISE_TERMS=YES,+
   TEXT=YES;
*
SEARCH_CONTROL_SET=TEXT_SEARCH,+
   STOP=(NUMBERS,DM_STOP_WORDS),+
   BREAK=(NON_GRAPHIC,' !!"#$%&()*+,-.:;<=>?@[\]^_{|}'),+
   SUB_BREAK=('''/'),+
   SINGULAR=YES,+
   PRECISION=30,+
   RAISE_TERMS=YES,+
   BLANK_CONTROL=YES,+
   TEXT=YES;
*
DOMAIN=DEPT_NO,+
   LEGAL=100: 999,+
   COMMENT=(+
   'Unique number identifies each department'),+
   PRECISION=3,+
   TYPE=EXACT_BINARY;
*
DOMAIN=EMP_NO,+
   LEGAL=ENORANGE,+
   COMMENT=(+
   'Unique number identifies each employee'),+
   PRECISION=5,+
   TYPE=EXACT_BINARY;
*
DOMAIN=PERSON_NAME,+
   SIZE=1:48,+
   EDIT_BLANKS=SQUEEZE,+
   PATTERN='A(1:15)-(0:1)A(0:15),BA(1:15)',+
   COMMENT=(+
   'Person name in Last, First format'),+
   SEARCH_CONTROL=RAISED,+
   TYPE=CHAR;
*
PARAMETER_SET=DEPT_NO,+
   LABEL='DeptNo',+
   OUTPUT_FORMAT=>6>,+
   OCCURS=1:1,+
   REFLECT=YES;
*
PARAMETER_SET=EMP_NO,+
   OUTPUT_FORMAT=>5>,+
   OCCURS=1:1,+
   REFLECT=YES;
*
PARAMETER_SET=MGR_NO,+
   LABEL='MgrNo',+
   OUTPUT_FORMAT=>5>,+
   OCCURS=1:1,+
   REFLECT=YES;
*
*
RECORD=CLIENT,STYLE=CONVENTIONAL;
*
FIELD=CITY,+
   LABEL='City',+
   OUTPUT_FORMAT=<20<,+
   SORT_SIZE=20,+
   OCCURS=0:1,+
   COMMENT=(+
   'Client''s city'),+
   DISPLAY_SEQUENCE_NUMBER=4,+
   SIZE=1:20,+
   TYPE=CHAR;
*
FIELD=CNAME,+
   LABEL='Name',+
   OUTPUT_FORMAT=<28/VR2<,+
   SORT_SIZE=48,+
   OCCURS=1:1,+
   DISPLAY_SEQUENCE_NUMBER=2,+
   DOMAIN=PERSON_NAME;
*
FIELD=CO,+
   LABEL='Company',+
   OUTPUT_FORMAT=<20/VR3<,+
   SORT_SIZE=50,+
   SEARCHED=YES,+
   OCCURS=0:1,+
   COMMENT=(+
   'Company name'),+
   DISPLAY_SEQUENCE_NUMBER=9,+
   SORT_STOPWORDS=(DM_LEAD_WORDS),+
   SIZE=1:50,+
   SEARCH_CONTROL=COSEARCH,+
   TYPE=CHAR;
*
FIELD=COUNTRY,+
   LABEL='Country',+
   OUTPUT_FORMAT=<15/VR2<,+
   SORT_SIZE=25,+
   OCCURS=0:1,+
   COMMENT=(+
   'Client''s country'),+
   DISPLAY_SEQUENCE_NUMBER=8,+
   SIZE=1:25,+
   TYPE=CHAR;
*
FIELD=ID,+
   LABEL='Client ID',+
   OUTPUT_FORMAT=<8<,+
   COMMENT=(+
   'System generated client number'),+
   DISPLAY_SEQUENCE_NUMBER=1,+
   USAGE=SYSTEM_KEY(1);
*
FIELD=LONG_STATE,+
   LABEL='Long State',+
   OUTPUT_FORMAT=<11/VR3<,+
   SORT_SIZE=30,+
   OCCURS=0:1,+
   COMMENT=(+
   'Client''s state or N/A'),+
   DISPLAY_SEQUENCE_NUMBER=6,+
   SIZE=0:30,+
   TRANSLATE=STATE,+
   TYPE=CHAR;
*
FIELD=NEWCO,+
   LABEL='New Company',+
   OUTPUT_FORMAT=<20/VR3<,+
   SORT_SIZE=50,+
   SEARCHED=YES,+
   OCCURS=0:2,+
   COMMENT=(+
   'Company name that doesn''t exist in the thesaurus.'),+
   DISPLAY_SEQUENCE_NUMBER=10,+
   SORT_STOPWORDS=(DM_LEAD_WORDS),+
   SIZE=1:50,+
   TYPE=CHAR;
*
FIELD=STATE,+
   LABEL='St.',+
   OUTPUT_FORMAT=<3<,+
   SORT_SIZE=3,+
   OCCURS=0:1,+
   COMMENT=(+
   'State abbreviations or N/A'),+
   DISPLAY_SEQUENCE_NUMBER=5,+
   CODE_LIST=STATE_ABBS,+
   SIZE=1:3,+
   TYPE=CHAR;
*
FIELD=STREET,+
   LABEL='Street',+
   OUTPUT_FORMAT=<25/VR2<,+
   SORT_SIZE=40,+
   SEARCHED=YES,+
   OCCURS=1:1,+
   COMMENT=(+
   'Client''s street'),+
   DISPLAY_SEQUENCE_NUMBER=3,+
   SIZE=1:40,+
   SEARCH_CONTROL=STREET,+
   TYPE=CHAR;
*
FIELD=ZIP,+
   LABEL='Zip Code',+
   OUTPUT_FORMAT=<10<,+
   SORT_SIZE=10,+
   OCCURS=0:1,+
   COMMENT=(+
   'Client''s zip code'),+
   DISPLAY_SEQUENCE_NUMBER=7,+
   SIZE=0:10,+
   TYPE=CHAR;
*
*
RECORD=DEPARTMENT,STYLE=CONVENTIONAL;
*
FIELD=BUILDING_NO,+
   LABEL='Bldg',+
   OUTPUT_FORMAT=>4>,+
   OCCURS=1:1,+
   COMMENT=(+
   'Building number'),+
   DISPLAY_SEQUENCE_NUMBER=4,+
   PRECISION=1,+
   LEGAL=1: 9,+
   TYPE=EXACT_BINARY;
*
FIELD=DNO,+
   UNIQUE=YES,+
   DISPLAY_SEQUENCE_NUMBER=2,+
   PARAMETER_SET=DEPT_NO,+
   DOMAIN=DEPT_NO;
*
FIELD=MANAGER,+
   ALIAS=(MGR_ENO,MGR),+
   UNIQUE=YES,+
   COMMENT=(+
   'Manager''s number'),+
   DISPLAY_SEQUENCE_NUMBER=3,+
   PARAMETER_SET=MGR_NO,+
   DOMAIN=EMP_NO;
*
FIELD=NAME,+
   LABEL='Department',+
   OUTPUT_FORMAT=<20/VR3<,+
   SORT_SIZE=40,+
   SEARCHED=YES,+
   OCCURS=1:1,+
   COMMENT=(+
   'Department name'),+
   DISPLAY_SEQUENCE_NUMBER=1,+
   SIZE=1:50,+
   EDIT_BLANKS=SQUEEZE,+
   SEARCH_CONTROL=RAISED,+
   TYPE=CHAR;
*
*
RECORD=DEPENDENT,STYLE=CONVENTIONAL;
*
FIELD=DEP_NO,+
   INIT=1,+
   LABEL='Depno',+
   OUTPUT_FORMAT=>5>,+
   OCCURS=1:1,+
   COMMENT=(+
   'Dependents numbered for each employee'),+
   DISPLAY_SEQUENCE_NUMBER=1,+
   PRECISION=2,+
   LEGAL=1: 20,+
   TYPE=EXACT_BINARY;
*
FIELD=ENO,+
   LABEL='ENO',+
   DISPLAY_SEQUENCE_NUMBER=2,+
   PARAMETER_SET=EMP_NO,+
   DOMAIN=EMP_NO;
*
FIELD=NAME,+
   LABEL='Dependent Name',+
   OUTPUT_FORMAT=<28/VR2<,+
   SORT_SIZE=48,+
   OCCURS=1:1,+
   DISPLAY_SEQUENCE_NUMBER=3,+
   DOMAIN=PERSON_NAME;
*
FIELD=RELATIONSHIP,+
   LABEL='Relationship',+
   OUTPUT_FORMAT=<12<,+
   SORT_SIZE=7,+
   OCCURS=1:1,+
   COMMENT=(+
   'Relationship of dependent to employee'),+
   DISPLAY_SEQUENCE_NUMBER=4,+
   LEGAL=RELATIONSHIP_LIST,+
   SIZE=1:7,+
   BLANK_CONTROL=YES,+
   RAISE_DATA=YES,+
   TYPE=CHAR;
*
FIELD=UDNO,+
   UNIQUE=YES,+
   LABEL='Unique Depno',+
   OUTPUT_FORMAT=>8>,+
   SET_WHEN=PUT,+
   OCCURS=1:1,+
   COMMENT=(+
   'Unique number that identifies each dependent'),+
   DISPLAY_SEQUENCE_NUMBER=5,+
   PRECISION=9,+
   SET_EXPR=$CONCATENATE(ENO,DEP_NO),+
   TYPE=EXACT_BINARY;
*
*
RECORD=EMPLOYEE,STYLE=CONVENTIONAL;
*
FIELD=COMM,+
   UNITS='DOLLARS',+
   LABEL='Com/Month',+
   OUTPUT_FORMAT=>9.2/C/DC>,+
   OCCURS=0:1,+
   COMMENT=(+
   'Employee monthly commission'),+
   DISPLAY_SEQUENCE_NUMBER=3,+
   PRECISION=6,+
   LEGAL=1.00: 4000.00,+
   USAGE=MONEY;
*
FIELD=DNO,+
   DISPLAY_SEQUENCE_NUMBER=2,+
   PARAMETER_SET=DEPT_NO,+
   DOMAIN=DEPT_NO;
*
FIELD=ENO,+
   UNIQUE=YES,+
   LABEL='ENO',+
   DISPLAY_SEQUENCE_NUMBER=4,+
   PARAMETER_SET=EMP_NO,+
   DOMAIN=EMP_NO;
*
FIELD=JOB,+
   LABEL='Job Title',+
   OUTPUT_FORMAT=<12/VR2<,+
   SORT_SIZE=3,+
   SEARCHED=YES,+
   OCCURS=1:1,+
   COMMENT=(+
   'Job title'),+
   DISPLAY_SEQUENCE_NUMBER=5,+
   LEGAL=JOB_LIST,+
   SIZE=1:24,+
   EDIT_BLANKS=SQUEEZE,+
   SEARCH_CONTROL=RAISED,+
   TYPE=CHAR;
*
FIELD=MGR_NO,+
   ALIAS=(MANAGER,MGR),+
   COMMENT=(+
   'Manager''s employee number'),+
   DISPLAY_SEQUENCE_NUMBER=6,+
   PARAMETER_SET=MGR_NO,+
   DOMAIN=EMP_NO;
*
FIELD=NAME,+
   LABEL='Name',+
   OUTPUT_FORMAT=<14/VR4<,+
   SORT_SIZE=48,+
   SEARCHED=YES,+
   OCCURS=1:1,+
   DISPLAY_SEQUENCE_NUMBER=1,+
   DOMAIN=PERSON_NAME;
*
FIELD=SALARY,+
   UNITS='DOLLARS',+
   LABEL='Sal/Month',+
   OUTPUT_FORMAT=>10.2/C/DC>,+
   SEARCHED=YES,+
   OCCURS=1:1,+
   COMMENT=(+
   'Employee monthly salary'),+
   DISPLAY_SEQUENCE_NUMBER=8,+
   PRECISION=7,+
   LEGAL=0.0: 10000.00,+
   USAGE=MONEY;
*
FIELD=TEL,+
   ALIAS=(EXT),+
   LABEL='Ext',+
   OUTPUT_FORMAT=>4>,+
   OCCURS=0:1,+
   COMMENT=(+
   'Phone extension of employee'),+
   DISPLAY_SEQUENCE_NUMBER=9,+
   PRECISION=4,+
   LEGAL=1: 9999,+
   TYPE=EXACT_BINARY;
*
*
RECORD=SCHED,STYLE=CONTINUOUS_DOCUMENT,PRIMARY_KEY=CLIENTDATE,+
   COMMENT=(+
$B,'Key formed in SDM using multi-field index');
*
FIELD=DEPARTURE,+
   LABEL='Depart date',+
   OUTPUT_FORMAT=<17/DATE4<,+
   OCCURS=1:1,+
   COMMENT=(+
   'Client''s date of departure'),+
   DISPLAY_SEQUENCE_NUMBER=4,+
   LEGAL=(DATE),+
   USAGE=DATE;
*
FIELD=DESTIN,+
   LABEL='Travel Stops',+
   OUTPUT_FORMAT=<20<,+
   SORT_SIZE=20,+
   SEARCHED=YES,+
   OCCURS=1:20,+
   COMMENT=(+
   'Cities where client stops'),+
   DISPLAY_SEQUENCE_NUMBER=3,+
   SIZE=1:20,+
   SEARCH_CONTROL=RAISED,+
   TYPE=CHAR;
*
FIELD=ENO,+
   LABEL='ENO',+
   COMMENT=(+
   'This employee scheduled the client''s trip'),+
   DISPLAY_SEQUENCE_NUMBER=2,+
   PARAMETER_SET=EMP_NO,+
   DOMAIN=EMP_NO;
*
FIELD=ID,+
   LABEL='Client ID',+
   OUTPUT_FORMAT=<8<,+
   OCCURS=1:1,+
   COMMENT=(+
   'Client''s ID number'),+
   DISPLAY_SEQUENCE_NUMBER=1,+
   PRECISION=8,+
   TYPE=EXACT_BINARY;
*
FIELD=ITIN,+
   LABEL='Itinerary',+
   OUTPUT_FORMAT=<70<,+
   SORT_SIZE=200,+
   OCCURS=0:1,+
   COMMENT=(+
   'Client''s itinerary for one complete trip'),+
   CONTEXT_UNIT=PARAGRAPH,+
   CONTEXT_PARSER=PARAGRAPH,+
   DISPLAY_SEQUENCE_NUMBER=5,+
   SIZE=1:500,+
   FORMAT=TEXT_IMAGE,+
   SEARCH_CONTROL=ITIN_SEARCH,+
   TYPE=CHAR;
*
FIELD=NOTES,+
   LABEL='Notes',+
   OUTPUT_FORMAT=<70<,+
   SORT_SIZE=200,+
   SEARCHED=YES,+
   OCCURS=0:1,+
   COMMENT=(+
   'Additional information about the itinerary'),+
   CONTEXT_UNIT=SENTENCE,+
   CONTEXT_PARSER=SENTENCE_ABBR,+
   DISPLAY_SEQUENCE_NUMBER=6,+
   SEARCH_CONTROL=TEXT_SEARCH,+
   USAGE=TEXT_STREAM;
*
FIELD_LIST=COMPANY, RECORD=CLIENT,+
   FIELDS=(CO,NEWCO);
*
FIELD_LIST=MAILING, RECORD=CLIENT,+
   FIELDS=(CNAME,CO,STREET,CITY,STATE,ZIP,COUNTRY);
*
FIELD_LIST=PHONE, RECORD=EMPLOYEE,+
   FIELDS=(NAME,ENO,DNO,TEL);
*
FIELD_LIST=TRAVEL, RECORD=SCHED,+
   FIELDS=(DESTIN,ITIN);
*
ASSERT(1) +
   ERROR_MESSAGE= 'All of department 101 needs to be located in    building +
3.' +
   FOR DEPARTMENT +
   IF DNO=101 +
   THEN BUILDING_NO=3 ;
*
ASSERT(2) +
   ERROR_MESSAGE= 'Commission is too    large for salary.  Give this person +
a raise!!' +
   FOR EMPLOYEE +
   CHECK COMM < 0.75 * SALARY ;
*
ASSERT(3) +
   ERROR_MESSAGE= 'This employee''s new salary must be     greater than the +
old salary.' +
   FOR EMPLOYEE +
   CHECK NEW SALARY >= OLD SALARY ;
*
ASSERT(4) +
   ERROR_MESSAGE= 'ENO must be a unique value.    An employee already exists+
 that has that number.' +
   UNIQUE EMPLOYEE.ENO;
*
ASSERT(5) +
   ADD_MEMBER_MESSAGE= 'Cannot add dependents to unknown employee.' +
   DEL_OWNER_MESSAGE= 'Cannot delete employee with dependents.' +
   UNIQUE EMPLOYEE OWNS DEPENDENT +
   IF EMPLOYEE.ENO=DEPENDENT.ENO;
*
ASSERT(6) +
   ADD_MEMBER_MESSAGE= 'Cannot add employee to an unknown department.' +
   DEL_OWNER_MESSAGE= 'Cannot delete department referenced by employees.' +
   UNIQUE DEPARTMENT OWNS EMPLOYEE +
   IF DEPARTMENT.DNO=EMPLOYEE.DNO;
*
ASSERT(7) +
   ADD_MEMBER_MESSAGE= 'Cannot add department with unknown manager.' +
   DEL_OWNER_MESSAGE= 'Cannot delete the manager of an existing department.' +
   UNIQUE EMPLOYEE OWNS DEPARTMENT +
   IF EMPLOYEE.ENO=DEPARTMENT.MANAGER;
*
ASSERT(8) +
   ADD_MEMBER_MESSAGE= 'Cannot add employee with unknown manager.' +
   DEL_OWNER_MESSAGE= 'Cannot delete the manager of existing employees.' +
   UNIQUE EMPLOYEE OWNS EMPLOYEE +
   IF EMPLOYEE.ENO=EMPLOYEE.MGR_NO;
*
ASSERT(9) +
   ADD_MEMBER_MESSAGE= 'Cannot add ID that''s not in the CLIENT record' +
   UNIQUE CLIENT OWNS SCHED +
   IF CLIENT.ID=SCHED.ID;
*
REVL RECORD=CLIENT;
*
IF ($EXISTS(STATE) NE 0)
  SET COUNTRY='USA';
ELSE
  SET STATE='N/A';
  CHECK COUNTRY, REQUIRED,   MESSAGE='You must enter the name of a country.';
END_IF;
THESAURUS=CODATA, FIELD=CO, RAISE=YES, RETURNS=WARNING, MESSAGE='This compan+
y needs to be added to the thesaurus.', EXCEPTIONS=NEWCO;
END_REVL;
*----------------------------------------
STRUCTURAL_DATA_MODEL;*          TOUR
*----------------------------------------
*
AREA=DMAREA,+
   ALLOCATION=DYNAMIC,+
   DEFAULT_RECORD_AREA=YES,+
   DEFAULT_INDEX_AREA=YES,+
   DEFAULT_QUEUE_AREA=NO,+
   PAGES_IN_AREA=250000;
*
AREA=DMQAREA,+
   ALLOCATION=DYNAMIC,+
   DEFAULT_RECORD_AREA=NO,+
   DEFAULT_INDEX_AREA=NO,+
   DEFAULT_QUEUE_AREA=YES,+
   PAGES_IN_AREA=250000;
*
FILE(1)='%BASIS_DB%\tour\rdb01',+
   AREAS=(DMAREA),+
   BACKUP_CYCLES=10;
*
FILE(2)='%BASIS_DB%\tour\rdb02',+
   AREAS=(DMQAREA),+
   BACKUP_CYCLES=10;
*
FILE(1)='%BASIS_DB%\tour\rdb01v01',+
   VERSION=1,+
   BACKUP_CYCLES=10;
*
FILE(2)='%BASIS_DB%\tour\rdb02v01',+
   VERSION=1,+
   BACKUP_CYCLES=10;
*
BACKUP_SET= 1,+
   USAGE=DATA,+
   TYPE=DIRECTORY,+
   ALLOCATION_REQUEST=('ASSLN BASIS$DB DRIVE'),+
   DENSITY=1600,+
   VOLUMES=1,+
   FILE=999,+
   METHOD=COPY;
*
JOURNAL A='%BASIS_DB%\tour\rja',+
   SAVE_BEFORE_IMAGES=NO,+
   BACKUP_CYCLES=10,+
   B='%BASIS_DB%\tour\rjb',+
   PAGES=1000;
*
JOURNAL A='%BASIS_DB%\tour\rja_v01',+
   VERSION=1,+
   SAVE_BEFORE_IMAGES=NO,+
   BACKUP_CYCLES=10,+
   B='%BASIS_DB%\tour\rjb_v01',+
   PAGES=1000;
*
*
DEFINITION_DATA_BASE='%BASIS_DB%\tour\ddb';
*
INDEX=CLIENT.CO/COSEARCH,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,SIZE=1:50),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=WORD),+
   TYPE=INCLUSIVE;
*
INDEX=CLIENT.ID,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=SEQUENTIAL,   PRECISION=30),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=UNIQUE;
*
INDEX CLIENT.NAME_CO+
  =$COMBINE(+
CNAME/SPEEDSEARCH,CO/COSEARCH),+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,SIZE=1:50),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=EXACT;
*
INDEX=CLIENT.NEWCO,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,SIZE=1:50),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=CONTEXT),+
   TYPE=EXACT;
*
INDEX=CLIENT.STREET/STREET,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,SIZE=1:40),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=WORD),+
   TYPE=INCLUSIVE;
*
INDEX SCHED.CLIENTDATE+
  =$CONCATENATE(+
ID,DEPARTURE),+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,SIZE=8:18),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=UNIQUE;
*
INDEX=DEPARTMENT.DNO,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,   PRECISION=30),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=UNIQUE;
*
INDEX=DEPARTMENT.MANAGER,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,   PRECISION=30),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=UNIQUE;
*
INDEX=DEPARTMENT.NAME/RAISED,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,SIZE=1:50),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=EXACT;
*
INDEX=DEPENDENT.ENO,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,   PRECISION=30),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=EXACT;
*
INDEX=DEPENDENT.UDNO,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,   PRECISION=30),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=UNIQUE;
*
INDEX=EMPLOYEE.DNO,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,   PRECISION=30),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=EXACT;
*
INDEX=EMPLOYEE.ENO,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,   PRECISION=30),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=UNIQUE;
*
INDEX=EMPLOYEE.JOB/RAISED,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,SIZE=1:24),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=EXACT;
*
INDEX=EMPLOYEE.MGR_NO,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,   PRECISION=30),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=EXACT;
*
INDEX=EMPLOYEE.NAME/RAISED,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,SIZE=1:48),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=EXACT;
*
INDEX=EMPLOYEE.SALARY,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,   PRECISION=30),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=EXACT;
*
INDEX=SCHED.DESTIN/RAISED,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,SIZE=1:20),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=CONTEXT),+
   TYPE=EXACT;
*
INDEX=SCHED.ID,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,INSERT_METHOD=RANDOM,   PRECISION=30),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=NONE),+
   TYPE=EXACT;
*
INDEX=SCHED.NOTES/TEXT_SEARCH,+
   AREA=DMAREA,+
   TERMS=(INDEX_NULLS=NO,SINGULAR=YES,INSERT_METHOD=RANDOM,SIZE=1:250),+
   REFERENCES=(INSERT_METHOD=RANDOM,PROXIMITY=WORD),+
   TYPE=INCLUSIVE;
*
RECORD_STORAGE=CLIENT,+
   QUEUE_AREA=DMQAREA,+
   UPDATE=IMMEDIATE,+
   INDEX_STRUCTURE=INDIRECT,+
   MULTI_FIELD_INDEX=YES,+
   AREAS=DMAREA;
*
RECORD_STORAGE=DEPARTMENT,+
   QUEUE_AREA=DMQAREA,+
   UPDATE=IMMEDIATE,+
   MULTI_FIELD_INDEX=YES,+
   AREAS=DMAREA;
*
RECORD_STORAGE=DEPENDENT,+
   QUEUE_AREA=DMQAREA,+
   UPDATE=IMMEDIATE,+
   MULTI_FIELD_INDEX=YES,+
   AREAS=DMAREA;
*
RECORD_STORAGE=EMPLOYEE,+
   QUEUE_AREA=DMQAREA,+
   UPDATE=IMMEDIATE,+
   MULTI_FIELD_INDEX=YES,+
   AREAS=DMAREA;
*
RECORD_STORAGE=SCHED,+
   QUEUE_AREA=DMQAREA,+
   UPDATE=IMMEDIATE,+
   MULTI_FIELD_INDEX=YES,+
   AREAS=DMAREA;
*
DDB_JOURNAL A='%BASIS_DB%\tour\dja',+
   SAVE_BEFORE_IMAGES=NO,+
   B='%BASIS_DB%\tour\djb',+
   PAGES=4000;
*----------------------------------
USER_DATA_MODEL;*          TOUR
MODEL=ADMIN,+
   ACCESS=PUBLIC,+
   TYPE=FQM;
*
VIEW=CLIENT,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(CLIENT),+
   FORM=NO;
*
FIELD=CITY,+
   LABEL='City',+
   OUTPUT_FORMAT=<20<,+
   SOURCE=CLIENT.CITY;
*
FIELD=CNAME,+
   LABEL='Name',+
   OUTPUT_FORMAT=<28/VR2<,+
   SOURCE=CLIENT.CNAME;
*
FIELD=CO,+
   LABEL='Company',+
   OUTPUT_FORMAT=<20/VR3<,+
   SOURCE=CLIENT.CO;
*
FIELD=COUNTRY,+
   LABEL='Country',+
   OUTPUT_FORMAT=<15/VR2<,+
   SOURCE=CLIENT.COUNTRY;
*
FIELD=ID,+
   LABEL='Client ID',+
   OUTPUT_FORMAT=<8<,+
   SOURCE=CLIENT.ID;
*
FIELD=LONG_STATE,+
   LABEL='Long State',+
   OUTPUT_FORMAT=<11/VR3<,+
   SOURCE=CLIENT.LONG_STATE;
*
FIELD=NEWCO,+
   LABEL='New Company',+
   OUTPUT_FORMAT=<20/VR3<,+
   SOURCE=CLIENT.NEWCO;
*
FIELD=STATE,+
   LABEL='St.',+
   OUTPUT_FORMAT=<3<,+
   SOURCE=CLIENT.STATE;
*
FIELD=STREET,+
   LABEL='Street',+
   OUTPUT_FORMAT=<25/VR2<,+
   SOURCE=CLIENT.STREET;
*
FIELD=ZIP,+
   LABEL='Zip Code',+
   OUTPUT_FORMAT=<10<,+
   SOURCE=CLIENT.ZIP;
*
VIEW=CLI_SCHED,+
   PRIVILEGES=(GET),+
   JOIN=(CLIENT.ID:=SCHED.ID),+
   SOURCE=(CLIENT,SCHED),+
   FORM=NO;
*
FIELD=CITY,+
   LABEL='City',+
   OUTPUT_FORMAT=<20<,+
   SOURCE=CLIENT.CITY;
*
FIELD=CNAME,+
   LABEL='Name',+
   OUTPUT_FORMAT=<28/VR2<,+
   SOURCE=CLIENT.CNAME;
*
FIELD=CO,+
   LABEL='Company',+
   OUTPUT_FORMAT=<20/VR3<,+
   SOURCE=CLIENT.CO;
*
FIELD=COUNTRY,+
   LABEL='Country',+
   OUTPUT_FORMAT=<15/VR2<,+
   SOURCE=CLIENT.COUNTRY;
*
FIELD=DEPARTURE,+
   LABEL='Depart date',+
   OUTPUT_FORMAT=<17/DATE4<,+
   SOURCE=SCHED.DEPARTURE;
*
FIELD=DESTIN,+
   LABEL='Travel Stops',+
   OUTPUT_FORMAT=<20<,+
   SOURCE=SCHED.DESTIN;
*
FIELD=ENO,+
   LABEL='ENO',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=SCHED.ENO;
*
FIELD=ID,+
   LABEL='Client ID',+
   OUTPUT_FORMAT=<8<,+
   SOURCE=SCHED.ID;
*
FIELD=ITIN,+
   LABEL='Itinerary',+
   OUTPUT_FORMAT=<70<,+
   SOURCE=SCHED.ITIN;
*
FIELD=LONG_STATE,+
   LABEL='Long State',+
   OUTPUT_FORMAT=<11/VR3<,+
   SOURCE=CLIENT.LONG_STATE;
*
FIELD=NEWCO,+
   LABEL='New Company',+
   OUTPUT_FORMAT=<20/VR3<,+
   SOURCE=CLIENT.NEWCO;
*
FIELD=NOTES,+
   LABEL='Notes',+
   OUTPUT_FORMAT=<70<,+
   SOURCE=SCHED.NOTES;
*
FIELD=STATE,+
   LABEL='St.',+
   OUTPUT_FORMAT=<3<,+
   SOURCE=CLIENT.STATE;
*
FIELD=STREET,+
   LABEL='Street',+
   OUTPUT_FORMAT=<25/VR2<,+
   SOURCE=CLIENT.STREET;
*
FIELD=ZIP,+
   LABEL='Zip Code',+
   OUTPUT_FORMAT=<10<,+
   SOURCE=CLIENT.ZIP;
*
VIEW=DEPARTMENT,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(DEPARTMENT),+
   FORM=NO;
*
FIELD=BUILDING_NO,+
   LABEL='Bldg',+
   OUTPUT_FORMAT=>4>,+
   SOURCE=DEPARTMENT.BUILDING_NO;
*
FIELD=DNO,+
   LABEL='DeptNo',+
   OUTPUT_FORMAT=>6>,+
   SOURCE=DEPARTMENT.DNO;
*
FIELD=MANAGER,+
   LABEL='MgrNo',+
   OUTPUT_FORMAT=>5>,+
   ALIAS=(MGR_ENO,MGR),+
   SOURCE=DEPARTMENT.MANAGER;
*
FIELD=NAME,+
   LABEL='Department',+
   OUTPUT_FORMAT=<20/VR3<,+
   SOURCE=DEPARTMENT.NAME;
*
VIEW=EMPLOYEE,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   WHERE=(EMPLOYEE.DNO=100),+
   SOURCE=(EMPLOYEE),+
   FORM=NO;
*
FIELD=COMM,+
   LABEL='Com/Month',+
   OUTPUT_FORMAT=>9.2/C/DC>,+
   SOURCE=EMPLOYEE.COMM;
*
FIELD=DNO,+
   LABEL='DeptNo',+
   OUTPUT_FORMAT=>6>,+
   SOURCE=EMPLOYEE.DNO;
*
FIELD=ENO,+
   LABEL='ENO',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=EMPLOYEE.ENO;
*
FIELD=JOB,+
   LABEL='Job Title',+
   OUTPUT_FORMAT=<12/VR2<,+
   SOURCE=EMPLOYEE.JOB;
*
FIELD=MGR_NO,+
   LABEL='MgrNo',+
   OUTPUT_FORMAT=>5>,+
   ALIAS=(MANAGER,MGR),+
   SOURCE=EMPLOYEE.MGR_NO;
*
FIELD=NAME,+
   LABEL='Name',+
   OUTPUT_FORMAT=<14/VR4<,+
   SOURCE=EMPLOYEE.NAME;
*
FIELD=SALARY,+
   LABEL='Sal/Month',+
   OUTPUT_FORMAT=>10.2/C/DC>,+
   SOURCE=EMPLOYEE.SALARY;
*
FIELD=TEL,+
   LABEL='Ext',+
   OUTPUT_FORMAT=>4>,+
   ALIAS=(EXT),+
   SOURCE=EMPLOYEE.TEL;
*
VIEW=SCHED,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(SCHED),+
   FORM=NO;
*
FIELD=DEPARTURE,+
   LABEL='Depart date',+
   OUTPUT_FORMAT=<17/DATE4<,+
   SOURCE=SCHED.DEPARTURE;
*
FIELD=DESTIN,+
   LABEL='Travel Stops',+
   OUTPUT_FORMAT=<20<,+
   SOURCE=SCHED.DESTIN;
*
FIELD=ENO,+
   LABEL='ENO',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=SCHED.ENO;
*
FIELD=ID,+
   LABEL='Client ID',+
   OUTPUT_FORMAT=<8<,+
   SOURCE=SCHED.ID;
*
FIELD=ITIN,+
   LABEL='Itinerary',+
   OUTPUT_FORMAT=<70<,+
   SOURCE=SCHED.ITIN;
*
FIELD=NOTES,+
   LABEL='Notes',+
   OUTPUT_FORMAT=<70<,+
   SOURCE=SCHED.NOTES;
*
*
MODEL=ALL,+
   ACCESS=PUBLIC,+
   TYPE=FQM;
*
VIEW=CLIENT,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(CLIENT),+
   FORM=NO;
*
FIELD=CITY,+
   LABEL='City',+
   OUTPUT_FORMAT=<20<,+
   SOURCE=CLIENT.CITY;
*
FIELD=CNAME,+
   LABEL='Name',+
   OUTPUT_FORMAT=<28/VR2<,+
   SOURCE=CLIENT.CNAME;
*
FIELD=CO,+
   LABEL='Company',+
   OUTPUT_FORMAT=<20/VR3<,+
   SOURCE=CLIENT.CO;
*
FIELD=COUNTRY,+
   LABEL='Country',+
   OUTPUT_FORMAT=<15/VR2<,+
   SOURCE=CLIENT.COUNTRY;
*
FIELD=ID,+
   LABEL='Client ID',+
   OUTPUT_FORMAT=<8<,+
   SOURCE=CLIENT.ID;
*
FIELD=LONG_STATE,+
   LABEL='Long State',+
   OUTPUT_FORMAT=<11/VR3<,+
   SOURCE=CLIENT.LONG_STATE;
*
FIELD=NEWCO,+
   LABEL='New Company',+
   OUTPUT_FORMAT=<20/VR3<,+
   SOURCE=CLIENT.NEWCO;
*
FIELD=STATE,+
   LABEL='St.',+
   OUTPUT_FORMAT=<3<,+
   SOURCE=CLIENT.STATE;
*
FIELD=STREET,+
   LABEL='Street',+
   OUTPUT_FORMAT=<25/VR2<,+
   SOURCE=CLIENT.STREET;
*
FIELD=ZIP,+
   LABEL='Zip Code',+
   OUTPUT_FORMAT=<10<,+
   SOURCE=CLIENT.ZIP;
*
VIEW=DEPARTMENT,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(DEPARTMENT),+
   FORM=NO;
*
FIELD=BUILDING_NO,+
   LABEL='Bldg',+
   OUTPUT_FORMAT=>4>,+
   SOURCE=DEPARTMENT.BUILDING_NO;
*
FIELD=DNO,+
   LABEL='DeptNo',+
   OUTPUT_FORMAT=>6>,+
   SOURCE=DEPARTMENT.DNO;
*
FIELD=MANAGER,+
   LABEL='MgrNo',+
   OUTPUT_FORMAT=>5>,+
   ALIAS=(MGR_ENO,MGR),+
   SOURCE=DEPARTMENT.MANAGER;
*
FIELD=NAME,+
   LABEL='Department',+
   OUTPUT_FORMAT=<20/VR3<,+
   SOURCE=DEPARTMENT.NAME;
*
VIEW=DEPENDENT,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(DEPENDENT),+
   FORM=NO;
*
FIELD=DEP_NO,+
   LABEL='Depno',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=DEPENDENT.DEP_NO;
*
FIELD=ENO,+
   LABEL='ENO',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=DEPENDENT.ENO;
*
FIELD=NAME,+
   LABEL='Dependent Name',+
   OUTPUT_FORMAT=<28/VR2<,+
   SOURCE=DEPENDENT.NAME;
*
FIELD=RELATIONSHIP,+
   LABEL='Relationship',+
   OUTPUT_FORMAT=<12<,+
   SOURCE=DEPENDENT.RELATIONSHIP;
*
FIELD=UDNO,+
   LABEL='Unique Depno',+
   OUTPUT_FORMAT=>8>,+
   SOURCE=DEPENDENT.UDNO;
*
VIEW=EMPLOYEE,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(EMPLOYEE),+
   FORM=NO;
*
FIELD=COMM,+
   LABEL='Com/Month',+
   OUTPUT_FORMAT=>9.2/C/DC>,+
   SOURCE=EMPLOYEE.COMM;
*
FIELD=DNO,+
   LABEL='DeptNo',+
   OUTPUT_FORMAT=>6>,+
   SOURCE=EMPLOYEE.DNO;
*
FIELD=ENO,+
   LABEL='ENO',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=EMPLOYEE.ENO;
*
FIELD=JOB,+
   LABEL='Job Title',+
   OUTPUT_FORMAT=<12/VR2<,+
   SOURCE=EMPLOYEE.JOB;
*
FIELD=MGR_NO,+
   LABEL='MgrNo',+
   OUTPUT_FORMAT=>5>,+
   ALIAS=(MANAGER,MGR),+
   SOURCE=EMPLOYEE.MGR_NO;
*
FIELD=NAME,+
   LABEL='Name',+
   OUTPUT_FORMAT=<14/VR4<,+
   SOURCE=EMPLOYEE.NAME;
*
FIELD=SALARY,+
   LABEL='Sal/Month',+
   OUTPUT_FORMAT=>10.2/C/DC>,+
   SOURCE=EMPLOYEE.SALARY;
*
FIELD=TEL,+
   LABEL='Ext',+
   OUTPUT_FORMAT=>4>,+
   ALIAS=(EXT),+
   SOURCE=EMPLOYEE.TEL;
*
VIEW=SCHED,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(SCHED),+
   FORM=NO;
*
FIELD=DEPARTURE,+
   LABEL='Depart date',+
   OUTPUT_FORMAT=<17/DATE4<,+
   SOURCE=SCHED.DEPARTURE;
*
FIELD=DESTIN,+
   LABEL='Travel Stops',+
   OUTPUT_FORMAT=<20<,+
   SOURCE=SCHED.DESTIN;
*
FIELD=ENO,+
   LABEL='ENO',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=SCHED.ENO;
*
FIELD=ID,+
   LABEL='Client ID',+
   OUTPUT_FORMAT=<8<,+
   SOURCE=SCHED.ID;
*
FIELD=ITIN,+
   LABEL='Itinerary',+
   OUTPUT_FORMAT=<70<,+
   SOURCE=SCHED.ITIN;
*
FIELD=NOTES,+
   LABEL='Notes',+
   OUTPUT_FORMAT=<70<,+
   SOURCE=SCHED.NOTES;
*
*
MODEL=DBA,+
   ACCESS=PUBLIC,+
   TYPE=FQM;
*
VIEW=CLIENT,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(CLIENT),+
   FORM=NO;
*
FIELD=CITY,+
   LABEL='City',+
   OUTPUT_FORMAT=<20<,+
   SOURCE=CLIENT.CITY;
*
FIELD=CNAME,+
   LABEL='Name',+
   OUTPUT_FORMAT=<28/VR2<,+
   SOURCE=CLIENT.CNAME;
*
FIELD=CO,+
   LABEL='Company',+
   OUTPUT_FORMAT=<20/VR3<,+
   SOURCE=CLIENT.CO;
*
FIELD=COUNTRY,+
   LABEL='Country',+
   OUTPUT_FORMAT=<15/VR2<,+
   SOURCE=CLIENT.COUNTRY;
*
FIELD=ID,+
   LABEL='Client ID',+
   OUTPUT_FORMAT=<8<,+
   SOURCE=CLIENT.ID;
*
FIELD=LONG_STATE,+
   LABEL='Long State',+
   OUTPUT_FORMAT=<11/VR3<,+
   SOURCE=CLIENT.LONG_STATE;
*
FIELD=NEWCO,+
   LABEL='New Company',+
   OUTPUT_FORMAT=<20/VR3<,+
   SOURCE=CLIENT.NEWCO;
*
FIELD=STATE,+
   LABEL='St.',+
   OUTPUT_FORMAT=<3<,+
   SOURCE=CLIENT.STATE;
*
FIELD=STREET,+
   LABEL='Street',+
   OUTPUT_FORMAT=<25/VR2<,+
   SOURCE=CLIENT.STREET;
*
FIELD=ZIP,+
   LABEL='Zip Code',+
   OUTPUT_FORMAT=<10<,+
   SOURCE=CLIENT.ZIP;
*
VIEW=DEPARTMENT,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(DEPARTMENT),+
   FORM=NO;
*
FIELD=BUILDING_NO,+
   LABEL='Bldg',+
   OUTPUT_FORMAT=>4>,+
   SOURCE=DEPARTMENT.BUILDING_NO;
*
FIELD=DNO,+
   LABEL='DeptNo',+
   OUTPUT_FORMAT=>6>,+
   SOURCE=DEPARTMENT.DNO;
*
FIELD=MANAGER,+
   LABEL='MgrNo',+
   OUTPUT_FORMAT=>5>,+
   ALIAS=(MGR_ENO,MGR),+
   SOURCE=DEPARTMENT.MANAGER;
*
FIELD=NAME,+
   LABEL='Department',+
   OUTPUT_FORMAT=<20/VR3<,+
   SOURCE=DEPARTMENT.NAME;
*
VIEW=DEPENDENT,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(DEPENDENT),+
   FORM=NO;
*
FIELD=DEP_NO,+
   LABEL='Depno',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=DEPENDENT.DEP_NO;
*
FIELD=ENO,+
   LABEL='ENO',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=DEPENDENT.ENO;
*
FIELD=NAME,+
   LABEL='Dependent Name',+
   OUTPUT_FORMAT=<28/VR2<,+
   SOURCE=DEPENDENT.NAME;
*
FIELD=RELATIONSHIP,+
   LABEL='Relationship',+
   OUTPUT_FORMAT=<12<,+
   SOURCE=DEPENDENT.RELATIONSHIP;
*
FIELD=UDNO,+
   LABEL='Unique Depno',+
   OUTPUT_FORMAT=>8>,+
   SOURCE=DEPENDENT.UDNO;
*
VIEW=EMPLOYEE,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(EMPLOYEE),+
   FORM=NO;
*
FIELD=COMM,+
   LABEL='Com/Month',+
   OUTPUT_FORMAT=>9.2/C/DC>,+
   SOURCE=EMPLOYEE.COMM;
*
FIELD=DNO,+
   LABEL='DeptNo',+
   OUTPUT_FORMAT=>6>,+
   SOURCE=EMPLOYEE.DNO;
*
FIELD=ENO,+
   LABEL='ENO',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=EMPLOYEE.ENO;
*
FIELD=JOB,+
   LABEL='Job Title',+
   OUTPUT_FORMAT=<12/VR2<,+
   SOURCE=EMPLOYEE.JOB;
*
FIELD=MGR_NO,+
   LABEL='MgrNo',+
   OUTPUT_FORMAT=>5>,+
   ALIAS=(MANAGER,MGR),+
   SOURCE=EMPLOYEE.MGR_NO;
*
FIELD=NAME,+
   LABEL='Name',+
   OUTPUT_FORMAT=<14/VR4<,+
   SOURCE=EMPLOYEE.NAME;
*
FIELD=SALARY,+
   LABEL='Sal/Month',+
   OUTPUT_FORMAT=>10.2/C/DC>,+
   SOURCE=EMPLOYEE.SALARY;
*
FIELD=TEL,+
   LABEL='Ext',+
   OUTPUT_FORMAT=>4>,+
   ALIAS=(EXT),+
   SOURCE=EMPLOYEE.TEL;
*
VIEW=SCHED,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(SCHED),+
   FORM=NO;
*
FIELD=DEPARTURE,+
   LABEL='Depart date',+
   OUTPUT_FORMAT=<17/DATE4<,+
   SOURCE=SCHED.DEPARTURE;
*
FIELD=DESTIN,+
   LABEL='Travel Stops',+
   OUTPUT_FORMAT=<20<,+
   SOURCE=SCHED.DESTIN;
*
FIELD=ENO,+
   LABEL='ENO',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=SCHED.ENO;
*
FIELD=ID,+
   LABEL='Client ID',+
   OUTPUT_FORMAT=<8<,+
   SOURCE=SCHED.ID;
*
FIELD=ITIN,+
   LABEL='Itinerary',+
   OUTPUT_FORMAT=<70<,+
   SOURCE=SCHED.ITIN;
*
FIELD=NOTES,+
   LABEL='Notes',+
   OUTPUT_FORMAT=<70<,+
   SOURCE=SCHED.NOTES;
*
*
MODEL=FQM,+
   ACCESS=PUBLIC,+
   TYPE=FQM;
*
VIEW=DEPENDENT,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(DEPENDENT),+
   FORM=NO;
*
FIELD=DEP_NO,+
   LABEL='Depno',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=DEPENDENT.DEP_NO;
*
FIELD=ENO,+
   LABEL='ENO',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=DEPENDENT.ENO;
*
FIELD=NAME,+
   LABEL='Dependent Name',+
   OUTPUT_FORMAT=<28/VR2<,+
   SOURCE=DEPENDENT.NAME;
*
FIELD=RELATIONSHIP,+
   LABEL='Relationship',+
   OUTPUT_FORMAT=<12<,+
   SOURCE=DEPENDENT.RELATIONSHIP;
*
FIELD=UDNO,+
   LABEL='Unique Depno',+
   OUTPUT_FORMAT=>8>,+
   SOURCE=DEPENDENT.UDNO;
*
VIEW=EMPLOYEE,+
   PRIVILEGES=(GET,ADD,MOD,DEL),+
   SOURCE=(EMPLOYEE),+
   FORM=NO;
*
FIELD=COMM,+
   LABEL='Com/Month',+
   OUTPUT_FORMAT=>9.2/C/DC>,+
   SOURCE=EMPLOYEE.COMM;
*
FIELD=DNO,+
   LABEL='DeptNo',+
   OUTPUT_FORMAT=>6>,+
   SOURCE=EMPLOYEE.DNO;
*
FIELD=ENO,+
   LABEL='ENO',+
   OUTPUT_FORMAT=>5>,+
   SOURCE=EMPLOYEE.ENO;
*
FIELD=JOB,+
   LABEL='Job Title',+
   OUTPUT_FORMAT=<12/VR2<,+
   SOURCE=EMPLOYEE.JOB;
*
FIELD=MGR_NO,+
   LABEL='MgrNo',+
   OUTPUT_FORMAT=>5>,+
   ALIAS=(MANAGER,MGR),+
   SOURCE=EMPLOYEE.MGR_NO;
*
FIELD=NAME,+
   LABEL='Name',+
   OUTPUT_FORMAT=<14/VR4<,+
   SOURCE=EMPLOYEE.NAME;
*
FIELD=SALARY,+
   LABEL='Sal/Month',+
   OUTPUT_FORMAT=>10.2/C/DC>,+
   SOURCE=EMPLOYEE.SALARY;
*
FIELD=TEL,+
   LABEL='Ext',+
   OUTPUT_FORMAT=>4>,+
   ALIAS=(EXT),+
   SOURCE=EMPLOYEE.TEL;
